Repository gustavo-alarcon/ms-softinvent, pull requests merged in 2019-05, with the labels that each got.

#2 Configuracion
  angular.json
  src/app/app.module.ts
  src/app/core/sidenav.service.ts
  src/app/main/main.component.html
  src/app/main/ms-config/ms-config-accounts/ms-config-accounts.component.html
  src/app/main/ms-config/ms-config-accounts/ms-config-accounts.component.ts
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-permits/ms-permits.component.html
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-permits/ms-permits.component.ts
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-sidenav-config-accounts.component.html
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-sidenav-config-accounts.component.ts
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-users/ms-users.component.html
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-users/ms-users.component.ts
  src/app/main/ms-config/ms-config-notifications/ms-config-notifications.component.html
  src/app/main/ms-config/ms-config-notifications/ms-config-notifications.component.ts
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-config-admin/ms-config-admin.component.html
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-config-admin/ms-config-admin.component.ts
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-config-staff/ms-config-staff.component.html
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-config-staff/ms-config-staff.component.ts
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-sidenav-config-notifications.component.html
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-sidenav-config-notifications.component.ts
  src/app/main/ms-config/ms-config.component.html
  src/app/main/ms-config/ms-config.component.ts
  src/app/routing/routing.module.ts
  src/styles.css
Labels: enhancement

#3 Ticket step 2
  angular.json
  src/app/app.module.ts
  src/app/core/sidenav.service.ts
  src/app/main/main.component.html
  src/app/ms-ticket2/ms-ticker2-stepper/ms-ticker2-stepper.component.html
  src/app/ms-ticket2/ms-ticker2-stepper/ms-ticker2-stepper.component.ts
  src/app/ms-ticket2/ms-ticker2-stepper/ms-ticket2-lista-detalle/ms-ticket2-lista-detalle.component.html
  src/app/ms-ticket2/ms-ticker2-stepper/ms-ticket2-lista-detalle/ms-ticket2-lista-detalle.component.ts
  src/app/ms-ticket2/ms-ticket2.component.html
  src/app/ms-ticket2/ms-ticket2.component.ts
  src/app/routing/routing.module.ts
Labels: enhancement

#4 ms-types
  src/app/app.module.ts
  src/app/core/ms-types.ts
  src/app/core/sidenav.service.ts
Labels: enhancement

#5 Correcciones color y tamanio
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.html
Labels: enhancement

#6 Agregar Tickets
  src/app/core/mattab.service.ts
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.ts
  src/app/ms-ticket/ms-ticket-stepper/ms-ticket-stepper.component.html
  src/app/ms-ticket/ms-ticket-stepper/ms-ticket-stepper.component.ts
Labels: enhancement

#7 Botones de eliminar tickets y productos en modulo Ticket y Ventas
  src/app/app.module.ts
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-product-search/ms-ticket-product-search.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-product-search/ms-ticket-product-search.component.ts
  src/app/routing/routing.module.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-product-search/ms-ventas-product-search.component.html
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-product-search/ms-ventas-product-search.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-step-one.component.html
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-step-one.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-three/ms-ventas-step-three.component.html
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-three/ms-ventas-step-three.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-two/ms-ventas-step-two.component.html
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-two/ms-ventas-step-two.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-stepper.component.html
  src/app/ventas/ms-ventas-stepper/ms-ventas-stepper.component.ts
  src/app/ventas/ms-ventas.component.html
  src/app/ventas/ms-ventas.component.ts
Labels: enhancement

#9 Correciones y configuraciones
  src/app/app.module.ts
  src/app/core/database.service.ts
  src/app/core/ms-types.ts
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/confirmacion-product/confirmacion-product.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-three/ms-ticket-step-three.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-three/ms-ticket-step-three.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/confirmacion-edit/confirmacion-edit.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/generar-ticket/generar-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/generar-ticket/generar-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
  src/app/ms-ticket/ms-ticket-stepper/ms-ticket-stepper.component.ts
  src/app/routing/routing.module.ts
Labels: enhancement

#10 Correcciones de Bugs
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/confirmacion-product/confirmacion-product.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/confirmacion-edit/confirmacion-edit.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
Labels: enhancement

#12 Tarea 11
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
Labels: enhancement

#15 Bugs
  src/app/core/ms-types.ts
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-step-one.component.ts
Labels: enhancement

#24 deploy
  .firebase/hosting.ZGlzdFxtcy1zb2Z0aW52ZW50.cache
  firebase.json
  src/app/app.module.ts
  src/app/core/auth.service.ts
  src/app/core/sidenav.service.ts
  src/app/core/state-management.service.ts
  src/app/main/main.component.html
  src/app/main/main.component.ts
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-users/ms-users.component.html
  src/app/main/ms-config/ms-config-accounts/ms-sidenav-config-accounts/ms-users/ms-users.component.ts
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-sidenav-config-notifications.component.html
  src/app/main/ms-config/ms-config-notifications/ms-sidenav-config-notifications/ms-sidenav-config-notifications.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/confirmacion-delete-ticket/confirmacion-delete-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/confirmacion-delete-ticket/confirmacion-delete-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-sidenav-tickets-products.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-description/ms-ticket-dialog-product-description.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-description/ms-ticket-dialog-product-description.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/confirmacion-delete/confirmacion-delete.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/confirmacion-delete/confirmacion-delete.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/edit-stock/edit-stock.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/edit-stock/edit-stock.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/generar-ticket/generar-ticket.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/no-stock/no-stock.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/no-stock/no-stock.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-one/ms-ventas-step-one.component.ts
  src/app/ventas/ms-ventas-stepper/ms-ventas-step-two/ms-ventas-step-two.component.ts
Labels: Caracteristica

#25 MEJORA : Checkbox funcionando
  src/app/core/ms-types.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
Labels: Caracteristica

#26 MEJORAS : ingles, botones y Nro de series
  src/app/core/database.service.ts
  src/app/core/ms-types.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-product-search/ms-ticket-product-search.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-step-one.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/edit-stock/edit-stock.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/editar-ticket/editar-ticket.component.ts
Labels: Caracteristica, Mejora

#27 MEJORA: aviso no stock
  src/app/app.module.ts
  src/app/core/state-management.service.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-one/ms-ticket-dialog-product-movement/ms-ticket-dialog-product-movement.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/edit-stock/edit-stock.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/edit-stock/edit-stock.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/generar-ticket/generar-ticket.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/ms-ticket-step-two.component.ts
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/no-stock/no-stock.component.html
  src/app/ms-ticket/ms-sidenav-tickets-products/ms-ticket-step-two/no-stock/no-stock.component.ts
Labels: Caracteristica
